name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install Local Package
        run: |
          pip install -e .[docs]
      - name: Copy Static Files
        run: |
          mkdir -p docs/source/_static
          cp assets/* docs/source/_static/
      - name: Sphinx Build
        run: |
          sphinx-build -b html docs/source _build
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.ACCOUNT_TOKEN }}
          publish_dir: _build/
          force_orphan: true
